---
title: "베이지안 통계"
filters:
   - lightbox
lightbox: auto
editor_options: 
  chunk_output_type: console
jupyter: python3
---

**동적가격책정(Dynamic Pricing)** 방법론으로 자주 언급되는 **톰슨 샘플링(Thompson Sampling)**은 베이지안 통계 방법론에 근간을 두고 있다. 
기존 사람이 다양한 연구를 바탕으로 가격을 선정하여 캠페인 등을 통해 실행에 옮기거나 A/B 테스팅과 같이 실험을 반복해서 주기적으로 최적 가격을 옮겨가는 방식이 아니라 톰슨 샘플링을 통해 최적의 가격을 실시간으로 책정하며 동적으로 유지하는 체계를 갖추기 위해 가장 기본이 되는 베타분포와 베르누이분포를 먼저 이해해야 한다.

톰슨 샘플링을 통해 풀려고 하는 문제는 가격정책을 몇가지로 지정한 후 예를 들어 3가지로 정했다고 가정하면 3가지 가격정책을 고객에게 보여주고 실시간으로 구매 혹은 비구매, 클릭 혹은 비클릭, 가입 혹은 비가입과 같은 성공 혹은 실패 결과를 얻고 이를 다시 가격정책에 반영하여 최적 가격을 찾아가는 방식이다.

이와 같은 동적 가격결정 방식을 구현하기 위해 수학적으로 가장 단순한 성공과 실패를 모형화하는데 베르누이 분포를 가정하고 지속적인 사후 확률분포 갱신을 위해 베르누이 분포의 켤레 사전분포로 베타분포를 선택하여 사후확률도 베타분포가 나오도록 하여 설계한다.


# 베타 분포

베타분포는 그 유연한 특성으로 인해 다양한 확률분포의 켤레 사전분포로 많이 활용된다. 예를 들어 서로 다른 3가지 가격 정책이 있는데 어느 가격대를 고객이 선택할지 모를 경우 균등분포로 두고 사후적으로 고객선택여부를 판정하고자 하는 경우 베타분포의 형태모수를 $\alpha =1, \beta=1$로 선정하면 자연스럽게 균등분포를 모형에 넣을 수 있게 된다.


## 감마와 베타 함수

베타함수는 다음과 같은 $\Gamma$ 함수로 표현할 수 있다. $\Gamma$ 함수는 자연수의 계승 또는 팩토리얼(factorial)을 의미하며 수식으로 표현하면 다음과 같다.

$$\Gamma(n) = (n-1)!$$

베타함수는 이항분포에 나오는 이항계수를 실수범위로 확장하여 일반화하는 형태로 알려져 있다.

$$Beta(\alpha, \beta)=\frac{\Gamma(\alpha)\,\Gamma(\beta)}{\Gamma(\alpha+\beta)}$$

## 베타 분포

베타분포는 베르누이, 이항, 음이항, 기하 분포의 켤레 사전분포(Conjugate Prior)이면서 0과 1사이 비율과 퍼센트지 무작위 사건을 모형화하는데 유용하다.
예를 들어, 구매/비구매, 전환율 등이 0과 1사이 비율을 갖는 비결정사건으로 대입해볼 수 있다.

[사후 확률(Posterior Probability)이 사전 확률(Prior Probability) 분포와 같은 분포 계열에 속하는 경우 그  사전확률분포를 **켤레 사전분포(Conjugate Prior)**라고 하고 이 경우 사후확률을 계산하기 쉬운 장점이 크다.]{.aside}

$$Beta(\alpha,\beta):\,\, prob(x|\alpha,\beta)=\frac{\Gamma(\alpha+\beta)}{{\Gamma(\alpha)\,\Gamma(\beta)}}x^{\alpha-1}(1-x)^{\beta-1}\\=\frac{x^{\alpha-1}(1-x)^{\beta-1}}{B(\alpha,\beta)}$$

베타분포의 평균과 분산은 $\alpha$와 $\beta$ 형태 모수를 사용하여 계산할 수 있다.

$$E(x)=\mu = \frac{\alpha}{\alpha + \beta}$$

$$V(x)=\frac{\alpha\beta}{(\alpha+\beta)^{2}(\alpha+\beta+1)}$$

## 시각화

예를 들어, $\alpha=2,\beta=2$ 형태모수를 갖는 $Beta(\alpha=2,\beta=2)$ 함수는 최고차항이 음의부호를 갖는 2차 방정식모양으로 표현할 수 있다. $\alpha,\beta$ 형태모수를 달리하여 0 과 1 사이 유연하게 다양한 함수형태를 모형화할 수 있는 것이 보여주고 있다.

$$Beta(\alpha=2,\beta=2):\,\, prob(x|\alpha,\beta)=\frac{\Gamma(2+2)}{{\Gamma(2)\,\Gamma(2)}}x^{2-1}(1-x)^{2-1}\\=\frac{\Gamma(4)}{{\Gamma(2)\,\Gamma(2)}}x(1-x)=상수\times(x-x^2)$$

```{python}
from scipy.stats import beta
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 1.0, 100)
y1 = beta.pdf(x, 0.5, 0.5)
y2 = beta.pdf(x, 2, 2)
y3 = beta.pdf(x, 2, 5)
y4 = beta.pdf(x, 5, 1)

plt.subplot(2, 2, 1) 
plt.title('Beta(a:0.5, b:0.5)')
plt.plot(x, y1, "r-")

plt.subplot(2, 2, 2) 
plt.title('Beta(a:2, b:2)')
plt.plot(x, y2, "g-")

plt.subplot(2, 2, 3) 
plt.title('Beta(a:2, b:5)')
plt.plot(x, y3, "b--")

plt.subplot(2, 2, 4) 
plt.title('Beta(a:5, b:1)')
plt.plot(x, y4, "b--")

plt.tight_layout()
plt.show()
```

## 베타분포 $\alpha, \beta$

베타분포 형태모수 $\alpha, \beta$를 달리할 때 분포의 모양을 살펴보자. 추후 베이지안 갱신을 통해 사후 베타분포가 베르누이 분포와 켤레분포로 사용될 경우 $\alpha, \beta$ 값을 성공과 실패로 갱신할 땔 분포의 변화를 이해하는데 도움이 될 것이다.

```{python}
# 데이터
x = np.linspace(0, 1.0, 100)
y11 = beta.pdf(x, 0.01, 0.01)
y12 = beta.pdf(x, 0.01, 1)
y13 = beta.pdf(x, 1, 0.01)
y21 = beta.pdf(x, 1, 1)
y22 = beta.pdf(x, 1, 2)
y23 = beta.pdf(x, 1, 3)
y31 = beta.pdf(x, 2, 1)
y32 = beta.pdf(x, 3, 1)
y33 = beta.pdf(x, 4, 1)
y41 = beta.pdf(x, 4, 2)
y42 = beta.pdf(x, 4, 3)
y43 = beta.pdf(x, 4, 4)

# 1번째 행 ===============
plt.subplot(4, 3, 1) 
plt.title('Beta(a:0, b:0)')
plt.plot(x, y11, "r-")

plt.subplot(4, 3, 2) 
plt.title('Beta(a:0, b:1)')
plt.plot(x, y12, "r-")

plt.subplot(4, 3, 3) 
plt.title('Beta(a:1, b:0)')
plt.plot(x, y13, "r-")

# 2번째 행 ===============
plt.subplot(4, 3, 4) 
plt.title('Beta(a:1, b:1)')
plt.plot(x, y21, "r-")

plt.subplot(4, 3, 5) 
plt.title('Beta(a:1, b:2)')
plt.plot(x, y22, "r-")

plt.subplot(4, 3, 6) 
plt.title('Beta(a:1, b:3)')
plt.plot(x, y23, "r-")

# 3번째 행 ===============
plt.subplot(4, 3, 7) 
plt.title('Beta(a:2, b:1)')
plt.plot(x, y31, "r-")

plt.subplot(4, 3, 8) 
plt.title('Beta(a:3, b:1)')
plt.plot(x, y32, "r-")

plt.subplot(4, 3, 9) 
plt.title('Beta(a:4, b:1)')
plt.plot(x, y33, "r-")

# 4번째 행 ===============
plt.subplot(4, 3, 10) 
plt.title('Beta(a:4, b:2)')
plt.plot(x, y41, "r-")

plt.subplot(4, 3, 11) 
plt.title('Beta(a:4, b:3)')
plt.plot(x, y42, "r-")

plt.subplot(4, 3, 12) 
plt.title('Beta(a:4, b:4)')
plt.plot(x, y43, "r-")

plt.tight_layout()
plt.show()

```


# 구매 사후확률 

## 구매 혹은 비구매

오프라인에서 고객별로 구매 혹은 비구매, 온라인에서는 구독 혹은 비구독, 클릭 혹은 비클릭 등과 같이 고객의 행동을 달리 표현할 수 있다. 이와 같은 구매 혹은 비구매는 성공 혹은 실패를 나타내는 베르누이 시행으로 표현할 수 있다. 여기서 $\theta$는 구매확률을 나타낸다.

$$X \sim Bernoulli (\theta)$$
확률밀도함수는 다음과 같다. 여기서 $\theta=0,1$ 성공과 실패값을 갖게 된다.

$$p(x|\theta) = \theta^x (1-\theta)^{1-x}$$

## 가능도

사후확률은 사전확률 곱하기 가능도로 정의된다.
따라서, 사전확률은 $Beta(\alpha, \beta)$로 정의하고 베르누이 가능도 함수를 구해 둘을 곱하게 되면 사후확률을 구할 수 있다. 먼저 가능도는 다음과 같이 계산된다.


$$
L(\theta;x) = p(\{x_i\}|\theta) = \prod_{i} p(x_i|\theta)\\ = \prod_{i} \theta^{x_i}(1-\theta)^{1-x_i}\\=\theta^{\sum_{i}{x_i}}(1-\theta)^{\sum_i{(1-x_i )}}\\=\theta^{구매횟수}(1-\theta)^{비구매횟수}
$$

## 사후확률

베르누이분포의 사전확률 켤레분포가 베타분포로 치환하여 둘을 곱하게 되면 사후확률을 구할 수 있다.

$$
p(\theta|z,N) = \frac{p(z,N|\theta)p(\theta)}{p(z,N)} \approx
L(\theta;x) \times p(\theta)
$$

사전분포를 베타분포로 두고 베르누이분포의 가능도 함수를 활용하여 사후확률을 구하면 다음과 같이 수식으로 표현할 수 있다.

$$
\begin{aligned}
p(\theta \mid X)
&\propto \theta^{\alpha + \sum x_t - 1} (1 - \theta)^{\beta + N - \sum x_t - 1}
\\
&\qquad \qquad \downarrow
\\
\theta \mid X &\sim \text{Beta}\Big(\alpha + \sum_{t=1}^{n} x_t, \beta + N - \sum_{t=1}^{n} x_t \Big).
\end{aligned}
$$

# 시각화

## 사전분포

양극단이 적고 중앙이 두툼한 형태 정규분포 비슷한 사전분포를 가정한다.

```{python}
plt.rcParams['font.family'] = 'NanumGothic'
x = np.linspace(0, 1.0, 100)
prior_y = beta.pdf(x, 2, 2)

plt.subplot(2, 2, 4) 
plt.title('사전분포 - 형태모수(a:2, b:2)를 갖는 베타분포')
plt.plot(x, prior_y, "b")

plt.tight_layout()
plt.show()


```

## 실제구매 데이터

고객 $N$ 명중 $n$ 명이 구매를 했다고 가정하자. 예를 들어, 
광고 캠페인에 $N=10$ 명에게 문자를 돌려 $n=6$이 구매를 한 경우 가능도를 아래와 같이 베타분포로 표현할 수 있다.

```{python}
import math

likelihoods = []

prob_space = np.linspace(0, 1.0, 100)

for i in range(0, len(prob_space)):
    likelihood = beta.pdf(prob_space[i], 10, 6)
    likelihoods.append(likelihood)
    # print(likelihood)

plt.plot(prob_space, likelihoods)
plt.title('가능도 함수 - 형태모수(\u03b1=6, \u03b2=4)를 갖는 베타분포')
plt.show()

prob_space[np.argmax(likelihoods)]
```


## 사후확률

베타분포를 사전확률로 갖고 베르누이/이항분포를 결합한 사후확률은 갱신된 형태모수 $\alpha, \beta$를 갖는 베타분포입니다. 따라서,

$$사전분포 \sim Beta(2,2) \qquad \rightarrow \qquad 사후분포 \sim Beta(2+6, 2+10-6)$$


```{python}
posteriors = []

prob_space = np.linspace(0, 1.0, 100)

for i in range(0, len(prob_space)):
    posterior = beta.pdf(prob_space[i], 8, 6)
    posteriors.append(posterior)
    # print(posterior)

plt.plot(prob_space, posteriors)
plt.title('사후분포  - 형태모수(\u03b1=8, \u03b2=6)를 갖는 베타분포')
plt.show()

prob_space[np.argmax(posteriors)]
```

## 결합

앞서 각기 달리 시각화한 것을 사전, 가능도, 사후 분포를 함께 살펴보자. 0.5 전후 구매확률이 있다고 사전분포를 가정한 후 실제 데이터를 통해 수집된 내용은 10명 중 6명이 구매를 한 것이 확인되었다. 이를 바탕으로 사전분포와 가능도를 결합하여 사후 구매확률을 자동으로 갱신할 수 있다.


:::{.panel-tabset}

### 나눠보기

```{python}

# 사전분포 ===============
plt.subplot(3, 1, 1)
x = np.linspace(0, 1.0, 100)
y_prior = beta.pdf(x, 2, 2)

plt.plot(x, y_prior, "g")
plt.title('Beta(\u03b1=2, \u03b2=2)')

# 가능도 분포 ===============
plt.subplot(3, 1, 2) 
plt.plot(prob_space, likelihoods, "b")
plt.title('"가능도 함수 - 형태모수(\u03b1=6, \u03b2=4)를 갖는 베타분포",')

# 사후분포 ===============
plt.subplot(3, 1, 3) 
plt.plot(prob_space, posteriors, "r")
plt.title('사후분포  - 형태모수(\u03b1=8, \u03b2=6)를 갖는 베타분포')

plt.tight_layout()
plt.show()
```

### 합쳐보기


```{python}

plt.title('사후분포  - 형태모수(\u03b1=8, \u03b2=6)를 갖는 베타분포')
# plt.subtitle('사전, 가능도, 사후 분포')

plt.plot(x, y_prior, "g")
plt.plot(prob_space, likelihoods, "b")
plt.plot(prob_space, posteriors, "r")

plt.legend(["사전분포", "가능도", "사후분포"], loc=1)
plt.tight_layout()
plt.show()
```

:::


