{
  "hash": "77c66c43da1a2467c340f24bf901272c",
  "result": {
    "markdown": "---\ntitle: \"가격결정 중요성\"\nfilters:\n   - lightbox\nlightbox: auto\neditor_options: \n  chunk_output_type: console\nknitr:\n  opts_chunk: \n    echo: true\n    waring: false\n    collapse: true\n    comment: \"#>\"\n---\n\n\n**가격(Price)**은 판매자가 판매하고 있는 제품과 서비스 가치를 반영하기에 적정 가격을 넘어 사업 목표를 달성할 수 있는 최적 가격을 제시하는 것이 매우 중요하다. 특히 가격은 **기업의 사업목표**를 달성하는 요소 중 가장 강력한 **정책수단**으로 인식되고 있다. \n\n**가격 결정요인**으로 **소비자**가 지불하고자 하는 가격은 가격의 상한을 설정하고 반대로 **원가**는 지속적인 생존과 성장을 위해 손해를 최소로 해야 하기 때문에 하한을 설정한다. 큰 틀에서 보면 원가와 고객이 중요하지만 이외에도 경쟁회사 가격, 유통경로와 납품구조, 정부 규제도 영향을 미친다.\n\n\n# 가격 설정 방법\n\n가격 결정방법은 다양한 방식이 존재한다. 예를 들어, 원가를 중시하여 결정을 하는 방식부터 고객과 가치를 핵심으로 두고 결정하는 방식, 시장상황을 반영하여 결정하는 방식 등 다양하다.\n\n- 비용+$\\alpha$ 방식 가격결정 방식: 비용 + 이익\n- 시장가 기준 가격결정 : 경쟁자 고려 가격 설정\n- 고객 중심 가격결정: 고객을 최우선 고려하여 가격 결정\n- 가치 중심 가격결정: 고객이 제품이과 서비스에 두는 가치를 근간으로 가격결정\n\n회사 내부적으로 각 부서별로 중요시하는 KPI/OKR이 다르기 때문에 고객에게 외부적으로 드러난 가격과 사내에서 설정하는 가격은 차이가 날 수 있다. 다음은 가격설정에 관여하는 부서와 중시하는 부분을 표로 정리한 것이다. 재무부서는 이익과 매출을 중시하기 때문에 사업목표 달성을 위해서 비용을 중시하여 비용+$\\alpha$ 가격결정방식을 선호하는 반면 \n영업과 마케팅 부서는 경쟁과 고객/가치를 중시하기 때문에 다른 가격결정방식을 선호한다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(gt)\n\npricing_tbl <- \n  tribble( ~ \"접근방식\",  ~\"중시\", ~\"무시\",    ~\"지지부서\",\n           \"비용+\",       \"비용\", \"경쟁, 고객\", \"재무\",\n           \"시장가 기반\", \"경쟁\", \"비용, 고객\", \"영업\",\n           \"가치 기반\",   \"고객\", \"비용, 경쟁\", \"마케팅\") \n\npricing_tbl %>% \n  gt() %>% \n    cols_align(\n      align = \"center\",\n      columns = everything()\n    )  %>% \n    tab_style(\n      style = cell_text(size = px(17)),\n      locations = cells_body(\n        columns = everything()\n      )\n    )  \n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"bswykqzlgv\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#bswykqzlgv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#bswykqzlgv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bswykqzlgv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#bswykqzlgv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#bswykqzlgv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bswykqzlgv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bswykqzlgv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#bswykqzlgv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#bswykqzlgv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#bswykqzlgv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#bswykqzlgv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#bswykqzlgv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#bswykqzlgv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#bswykqzlgv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#bswykqzlgv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#bswykqzlgv .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#bswykqzlgv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bswykqzlgv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#bswykqzlgv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#bswykqzlgv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bswykqzlgv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#bswykqzlgv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#bswykqzlgv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bswykqzlgv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bswykqzlgv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#bswykqzlgv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#bswykqzlgv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bswykqzlgv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bswykqzlgv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bswykqzlgv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bswykqzlgv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bswykqzlgv .gt_left {\n  text-align: left;\n}\n\n#bswykqzlgv .gt_center {\n  text-align: center;\n}\n\n#bswykqzlgv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#bswykqzlgv .gt_font_normal {\n  font-weight: normal;\n}\n\n#bswykqzlgv .gt_font_bold {\n  font-weight: bold;\n}\n\n#bswykqzlgv .gt_font_italic {\n  font-style: italic;\n}\n\n#bswykqzlgv .gt_super {\n  font-size: 65%;\n}\n\n#bswykqzlgv .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#bswykqzlgv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#bswykqzlgv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#bswykqzlgv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#bswykqzlgv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#bswykqzlgv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#bswykqzlgv .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\">접근방식</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\">중시</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\">무시</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\">지지부서</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_center\" style=\"font-size: 17px;\">비용+</td>\n<td class=\"gt_row gt_center\" style=\"font-size: 17px;\">비용</td>\n<td class=\"gt_row gt_center\" style=\"font-size: 17px;\">경쟁, 고객</td>\n<td class=\"gt_row gt_center\" style=\"font-size: 17px;\">재무</td></tr>\n    <tr><td class=\"gt_row gt_center\" style=\"font-size: 17px;\">시장가 기반</td>\n<td class=\"gt_row gt_center\" style=\"font-size: 17px;\">경쟁</td>\n<td class=\"gt_row gt_center\" style=\"font-size: 17px;\">비용, 고객</td>\n<td class=\"gt_row gt_center\" style=\"font-size: 17px;\">영업</td></tr>\n    <tr><td class=\"gt_row gt_center\" style=\"font-size: 17px;\">가치 기반</td>\n<td class=\"gt_row gt_center\" style=\"font-size: 17px;\">고객</td>\n<td class=\"gt_row gt_center\" style=\"font-size: 17px;\">비용, 경쟁</td>\n<td class=\"gt_row gt_center\" style=\"font-size: 17px;\">마케팅</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n  \n  \n\n# 가격변동과 판매량\n\n커피숍을 운영한다고 가정하자. 과거 경험에서 다음과 같은 경험치를 데이터를 통해 얻었다고 하면 이를 시각화하는 것은 어렵지 않을 것이다. 즉, 커피값이 1,000 원에서는 판매가 많지만 5,000원 넘어가면 판매가 거의 없고 대략 2,000원 전후로 가장 많은 수요가 있다는 것을 확인할 수 있다.\n\n:::{.callout-note}\n\n### 데이터의 중요성\n\n가격은 최종적으로 판매자와 생산자가 고객에게 제시하는 가치를 포괄적으로 담은 메시지다. 가격이 담긴 메시지에 따라 구매고객이 달라지고 당연히 매출도 영향을 크게 받는다. \n따라서, 기존 가격별 구매이력을 데이터로 담아 축적된 경험이 미래 설정할 가격결정에 큰 도움이 되는 것은 당연하다.\n:::\n  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(showtext)\nlibrary(patchwork)\n\nfont_add_google(\"Nanum Gothic\", \"NanumGothic\")\n\nshowtext_auto()\n\nwindows()\n\n## 1. 데이터 -------------\ncoffee_tbl <- tribble(~\"가격\", ~\"수요\",\n                      1000, 120,\n                      2000, 80,\n                      3000, 40,\n                      4000, 20)\n\n## 2. 수요와 가격 -------------\ncoffee_price_g <- coffee_tbl %>% \n  ggplot(aes(x = 가격, y = 수요, \n             ymax = 수요, ymin = 0)) +\n    geom_point(size = 3) +\n    geom_pointrange(color = \"gray50\", linetype = 2) +\n    expand_limits(x = 0, y = 0) +\n    scale_x_continuous(expand = expansion(mult = c(0, .1)),\n                       labels = scales::comma,\n                       limits = c(0, 5000)) +\n    scale_y_continuous(breaks=seq(0, 150, 20),\n                       expand = expansion(mult = c(0, .1))) +\n    theme_bw(base_family = \"NanumGothic\") +\n    labs(x = \"가격(원)\",\n         y = \"커피 수요(판매량)\",\n         title = \"커피 판매가격과 수요량 관계\")  \n\n## 3. 매출 -------------\ncoffee_revenue_g <- coffee_tbl %>% \n  mutate( 매출 = (가격 * 수요) / 10^4) %>% \n  # mutate(가격 = as.factor(가격)) %>% \n  ggplot(aes( x = 가격, y = 매출)) +\n    geom_col(fill = \"skyblue\", width = 200) +\n    scale_x_continuous(expand = expansion(mult = c(0, .1)),\n                       labels = scales::comma,\n                       limits = c(0, 5000)) +\n    theme_bw(base_family = \"NanumGothic\") +\n    labs(x = \"커피 가격\",\n         y = \"매출(만원)\",\n         title = \"커피 판매가격과 수요량 관계\")  \n\ncoffee_price_g / coffee_revenue_g\n```\n\n::: {.cell-output-display}\n![](pricing_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\n::: {.column-margin}\n\n**수요공급 곡선**\n\n[econocharts package](https://github.com/R-CoderDotCom/econocharts)를 사용해서 수월히 수요공급을 통한 가격 결정상황을 시각적으로 표현할 수 있다. 공급이 가격의 변화에 따라 직선이 아니지만 개념적으로 공급이 고정된 상황에서 수요가 늘어나게 되면 가격은 자연히 높아지게 된다. 반대로 수요가 줄어들게 되면 가격은 낮아진다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# devtools::install_github(\"R-CoderDotCom/econocharts\")\nlibrary(econocharts)\n#> ~~ Package econocharts\n#> Visit https://r-coder.com/ for R tutorials ~~\nlibrary(tidyverse)\n\nsupply_tbl     <- data.frame(x = c(1, 9), y = c(1, 9))\n\ndemand_tbl     <- data.frame(x = c(7, 1), y = c(1, 7))\nnew_demand_tbl <- data.frame(x = c(9, 1), y = c(1, 9))\n\nsdcurve_g <- sdcurve(supply_tbl, \n                     demand_tbl,\n                     supply_tbl, \n                     new_demand_tbl,\n                     names = c(\"S[1]\", \"D[현재]\",\"S[1]\", \"D[신규]\"),  \n                     equilibrium = TRUE) +\n  annotate(\"segment\", x = 1.1, xend = 2.8, y = 7, yend = 7, \n           arrow = arrow(length = unit(0.3, \"lines\")), colour = \"grey50\") +\n  annotate(\"segment\", x = 1, xend = 1, y = 4.1, yend = 4.9,               \n           arrow = arrow(length = unit(0.3, \"lines\")), colour = \"grey50\") +\n  annotate(\"segment\", x = 4.1, xend = 4.9, y = 1, yend = 1,               \n           arrow = arrow(length = unit(0.3, \"lines\")), colour = \"grey50\") +  \n  labs(title = \"수요 증가에 따른 가격과 공급량 변화\",\n       x = \"공급\",\n       y = \"가격\") +\n  theme_bw(base_family = \"NanumGothic\")    \n#> # A tibble: 2 × 2\n#>       x     y\n#>   <dbl> <dbl>\n#> 1     4     4\n#> 2     5     5\n\nsdcurve_g\n```\n\n::: {.cell-output-display}\n![](pricing_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n:::\n\n# 가격차별 이유\n\n가격과 수요물량에 대한 정보를 갖고 있는 상황에서 가격을 달리하여 매출과 순이익 변화를 살펴보자. 이를 통해서 적절한 가격결정과 가격정책의 중요성을 음미해보자.\n\n:::{.callout-warning}\n### TL;DR (Too Long; Didn't Read)\n\n동일한 제품과 서비스에 가격을 달리하면 이익을 높일 수 있다.\n:::\n\n## 데이터\n\n[데이터셋 출처: The Incremental Contribution from Segmented Price Structure [@nagle2017strategy]]{.aside}\n\n고객군을 분리하지 않은 단일 가격을 지정할 때, 고객군을 두개로 분리하여 가격을 2개 달리하여 책정할 때, 마지막으로 고객군을 5개로 세분화할 경우 발생되는 총이익을 살펴보자.\n\n- 고정비: 세가지 가격정책 모두 동일함 가정\n- 변동비: $5 달러로 가정.\n\n경제학을 비롯한 사회과학에서 가정이 중요하다. 가정을 통해 복잡한 문제를 단순화하고 이를 논리적 추론을 통해 결론에 빠르게 도달할 수 있는 장점이 있지만 가정이 무너지게 되면 이를 통해 도출한 결론도 달라질 수 있다. 고정비가 3가지 경우 모두 동일하다고 가정했지만 커피판매량이 늘어나게 되면 추가로 커피머신(업소용 커피머신이 대당 천만원 소요)이 필요하여 고정비가 늘어나게 된다. 반면에 변동비 $5 달러 가정은 커피 판매량에 따라 더 줄어들 수 있지만 (대량 구매에 따른 높은 할인율 적용) 그 효과가 크지 않다고 보면 결론을 뒤바뀔 정도로 크지 않은 합리적이고 안정적인 가정이라고 볼 수 있다. \n\n커피가격이 높을 때는 수요물량이 적고 커피가격이 낮은 경우 수요물량이 많은 것이 데이터를 통해 확인된다. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggforce)\n\nsegment_tbl <- tibble( x = c(50, \n                             50+150, \n                             50+150+350, \n                             50+150+350+250,\n                             50+150+350+250+200),\n                       y = c(20, 15, 10, 8, 6))\n\nsegment_tbl %>% \n  ggplot(aes(x = x, y = y)) +\n    geom_point() +\n    labs(x = \"수요물량\",\n         y = \"가격\",\n         title = \"가격과 수요물량 관계\") +\n     geom_hline(yintercept = 5, linetype = 2, color = \"gray70\") +\n     expand_limits(x =0, y =0) +\n     theme_bw(base_family = \"NanumGothic\") +\n     annotate(\"text\", x = 1, y = 6, label = \"변동비\", size = 3)\n```\n\n::: {.cell-output-display}\n![](pricing_files/figure-html/data-1.png){width=672}\n:::\n:::\n\n\n\n\n## 5개 가격\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfive_price_profit <- segment_tbl %>% \n  mutate(lag_x = lag(x)) %>% \n  mutate(수요물량 = ifelse(is.na(lag_x), x, x - lag_x)) %>% \n  rename(\"가격\" = y) %>% \n  mutate(공헌이익 = 가격 - 5) %>%  # 변동비용 제외\n  mutate(이익 = 수요물량 * 공헌이익) %>% \n  summarise(총이익 = sum(이익)) %>% \n  pull(총이익)\n\nfive_price_profit\n#> [1] 4950\n```\n:::\n\n\n서로 다른 가격정책을 5개 달리하게 되면 다음과 같이 4,950 을 얻게되어 가장 많은 이익을 남기게 된다. 이를 시각적으로 표현하면 가격과 판매량(수요물량)을 곱하게 되면 매출이 되고 변동비에 판매량(수요물량)을 곱하게 되면 비용이 되어 매출에서 비용을 빼게 되면 순이익이 된다. 가격을 5가지로 달리했기 때문에 5번 공식을 적용하여 더하게 되면 서로 다른 5개를 적용한 가격정책에 따른 순수 이익을 구할 수 있다.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggrepel)\n\nfive_price_g <- segment_tbl %>% \n  ggplot(aes(x = x, y = y)) +\n    expand_limits(x =0, y =0) +\n    geom_point(color = \"red\") +\n    geom_rect(aes(xmin = 0, xmax = 50, \n                  ymin = 0, ymax = 20), fill = \"gray50\") +\n    geom_rect(aes(xmin = 50, xmax = 50 + 150, \n                  ymin = 0, ymax = 15), fill = \"gray60\") +\n    geom_rect(aes(xmin = 50 + 150, xmax = 50 + 150 + 350, \n                  ymin = 0, ymax = 10), fill = \"gray70\") +\n    geom_rect(aes(xmin = 50 + 150 + 350, xmax = 50 + 150 + 350 + 250, \n                  ymin = 0, ymax = 8), fill = \"gray80\") +\n    geom_rect(aes(xmin = 50 + 150 + 350 +250, xmax = 50 + 150 + 350 + 250 +200, \n                  ymin = 0, ymax = 6), fill = \"gray90\")  +\n  ## 변동비 ------------\n    geom_rect(aes(xmin = 0, xmax = 50 + 150 + 350 + 250 +200, \n                  ymin = 0, ymax = 5), fill = \"white\", alpha = 0.1, color = \"blue\", linetype = \"dashed\")  +\n    labs(x = \"수요물량\",\n         y = \"가격\",\n         title = \"가격과 수요물량 관계: 서로 다른 5개 가격\") +\n     geom_hline(yintercept = 5, linetype = 2, color = \"gray70\") +\n     expand_limits(x =0, y =0) +\n     theme_bw(base_family = \"NanumGothic\") +\n     annotate(\"text\", x = 20, y = 6, label = \"변동비($5)\", size = 3)  +\n     scale_x_continuous(labels = scales::comma,\n                        breaks = c(0, 50, 50+150, 50+150+350, 50+150+350+250, 50+150+350+250+200)) +\n    geom_text_repel(aes(x = x, y =y, label = glue::glue(\"가격:{y}\\n물량:{x}\"))) +\n    annotate(\"text\", x = 500, y = 15, \n             label = glue::glue(\"총이익: {scales::comma(five_price_profit)}\"),\n             size = 5,\n             color = \"red\")  \n\nfive_price_g\n```\n\n::: {.cell-output-display}\n![](pricing_files/figure-html/five-price-1.png){width=672}\n:::\n:::\n\n\n\n## 2개 가격\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntwo_price_profit <- segment_tbl %>% \n  mutate(lag_x = lag(x)) %>% \n  mutate(수요물량 = ifelse(is.na(lag_x), x, x - lag_x)) %>% \n  rename(\"가격\" = y) %>% \n  mutate(공헌이익 = 가격 - 5) %>%  # 변동비용 제외\n  select(가격, 공헌이익, 수요물량) %>% \n  mutate(가격정책 = case_when(가격 %in% c(20, 15) ~ \"고가\", \n                              가격 %in% c(10, 8)  ~ \"중가\", \n                              TRUE ~ \"저가\")) %>% \n  filter(가격정책 != \"저가\") %>% \n  group_by(가격정책) %>% \n  summarise(물량 = sum(수요물량),\n            공헌이익 = min(공헌이익)) %>% \n  mutate(이익 = 물량 * 공헌이익) %>% \n  summarise(총이익 = sum(이익)) %>% \n  pull(총이익)\n\ntwo_price_profit\n#> [1] 3800\n```\n:::\n\n\n서로 다른 가격정책을 2개로 달리하게 되면 다음과 같이 3,800 을 얻게 되어 중간 정도 이익을 남기게 된다.\n서로 다른 5개 가격정책 대신 2가지 가격정책을 실행에 옮겼을 때 동일한 로직을 동원하여 총이익을 시각화하면 다음과 같다. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggrepel)\n\ntwo_price_g <- segment_tbl %>% \n  mutate(color = ifelse(y %in% c(15,8), \"red\", \"black\")) %>% \n  ggplot(aes(x = x, y = y)) +\n    expand_limits(x =0, y =0) +\n    geom_point(aes(color = color)) +\n    geom_rect(aes(xmin = 0, xmax = 50, \n                  ymin = 0, ymax = 20), \n              alpha = 0.0, color = \"black\", linetype = \"dashed\") +\n    geom_rect(aes(xmin = 0, xmax = 50 + 150, \n                  ymin = 0, ymax = 15), fill = \"gray60\") +\n    geom_rect(aes(xmin = 50 + 150, xmax = 50 + 150 + 350, \n                  ymin = 0, ymax = 10), \n              alpha = 0.0, color = \"black\", linetype = \"dashed\") +\n    geom_rect(aes(xmin = 50 + 150, xmax = 50 + 150 + 350 + 250, \n                  ymin = 0, ymax = 8), fill = \"gray80\") +\n    geom_rect(aes(xmin = 50 + 150 + 350 +250, xmax = 50 + 150 + 350 + 250 +200, \n                  ymin = 0, ymax = 6), \n              alpha = 0.0, color = \"black\", linetype = \"dashed\") +\n    ## 변동비 -------\n    geom_rect(aes(xmin = 0, xmax = 50 + 150 + 350 + 250 +200, \n                  ymin = 0, ymax = 5), fill = \"white\", alpha = 0.1, color = \"blue\", linetype = \"dashed\")  +\n    labs(x = \"수요물량\",\n         y = \"가격\",\n         title = \"가격과 수요물량 관계: 서로 다른 2개 가격\") +\n     geom_hline(yintercept = 5, linetype = 2, color = \"gray70\") +\n     expand_limits(x =0, y =0) +\n     theme_bw(base_family = \"NanumGothic\") +\n     annotate(\"text\", x = 20, y = 6, label = \"변동비($5)\", size = 3)  +\n     scale_x_continuous(labels = scales::comma,\n                        breaks = c(0, 50, 50+150, 50+150+350, 50+150+350+250, 50+150+350+250+200)) +\n    geom_text_repel(aes(x = x, y =y, label = glue::glue(\"가격:{y}\\n물량:{x}\"))) +\n    scale_color_manual(values = c(\"black\" = \"black\", \"red\" = \"red\")) +\n    theme(legend.position = \"none\")  +\n    annotate(\"text\", x = 500, y = 15, \n           label = glue::glue(\"총이익: {scales::comma(two_price_profit)}\"),\n           size = 5,\n           color = \"red\")\n\ntwo_price_g\n```\n\n::: {.cell-output-display}\n![](pricing_files/figure-html/two-price-1.png){width=672}\n:::\n:::\n\n\n\n## 1물 1가\n\n\n::: {.cell}\n\n```{.r .cell-code}\none_price_profit <- segment_tbl %>% \n  mutate(lag_x = lag(x)) %>% \n  mutate(수요물량 = ifelse(is.na(lag_x), x, x - lag_x)) %>% \n  rename(\"가격\" = y) %>% \n  mutate(공헌이익 = 가격 - 5) %>%  # 변동비용 제외\n  filter(가격 >= 10) %>% \n  summarise(물량 = sum(수요물량)) %>% \n  mutate(총이익 = 물량 * 5) %>% \n  pull(총이익)\n\none_price_profit\n#> [1] 2750\n```\n:::\n\n\n서로 다른 가격정책을 1개로 통일하면 다음과 같이 2,750 을 얻게되어 가장 적은 이익을 남기게 된다.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n\none_price_g <- segment_tbl %>% \n  mutate(color = ifelse(y == 10, \"red\", \"black\")) %>% \n  ggplot(aes(x = x, y = y)) +\n    expand_limits(x =0, y =0) +\n    geom_point(aes(color = color)) +\n    geom_rect(aes(xmin = 0, xmax = 50, \n                  ymin = 0, ymax = 20), \n              alpha = 0.0, color = \"black\", linetype = \"dashed\") +\n    geom_rect(aes(xmin = 50, xmax = 50 + 150, \n                  ymin = 0, ymax = 15), \n              alpha = 0.0, color = \"black\", linetype = \"dashed\") +\n    geom_rect(aes(xmin = 0, xmax = 50 + 150 + 350, \n                  ymin = 0, ymax = 10), fill = \"gray50\") +\n    geom_rect(aes(xmin = 50 + 150 +350, xmax = 50 + 150 + 350 + 250, \n                  ymin = 0, ymax = 8),\n              alpha = 0.0, color = \"black\", linetype = \"dashed\") +\n    geom_rect(aes(xmin = 50 + 150 + 350 +250, xmax = 50 + 150 + 350 + 250 +200, \n                  ymin = 0, ymax = 6), \n              alpha = 0.0, color = \"black\", linetype = \"dashed\") +\n    ## 변동비 -------\n    geom_rect(aes(xmin = 0, xmax = 50 + 150 + 350 + 250 +200, \n                  ymin = 0, ymax = 5), fill = \"white\", alpha = 0.1, color = \"blue\", linetype = \"dashed\")  +\n    labs(x = \"수요물량\",\n         y = \"가격\",\n         title = \"가격과 수요물량 관계: 1 가격\") +\n     geom_hline(yintercept = 5, linetype = 2, color = \"gray70\") +\n     expand_limits(x =0, y =0) +\n     theme_bw(base_family = \"NanumGothic\") +\n     annotate(\"text\", x = 20, y = 6, label = \"변동비($5)\", size = 3)  +\n     scale_x_continuous(labels = scales::comma,\n                        breaks = c(0, 50, 50+150, 50+150+350, 50+150+350+250, 50+150+350+250+200)) +\n    geom_text_repel(aes(x = x, y =y, label = glue::glue(\"가격:{y}\\n물량:{x}\"))) +\n    scale_color_manual(values = c(\"black\" = \"black\", \"red\" = \"red\")) +\n    theme(legend.position = \"none\") +\n    annotate(\"text\", x =500, y = 15, \n             label = glue::glue(\"총이익: {scales::comma(one_price_profit)}\"),\n             size = 5,\n             color = \"red\")\n\none_price_g\n```\n\n::: {.cell-output-display}\n![](pricing_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n## 가격정책 비교\n\n가격정책을 단일가, 2가지 가격, 5가지 가격을 달리 책정했을 경우 다른 조건을 모두 동일하게 두었을 경우(ceteris paribus 가정아래) 영업성과가 달라지는 것을 확인할 수 있다. 즉, 가격을 세분화하여 고객별로 달리 적용하면 총이익이 늘어나는 것을 알 수 있다.\n\n> **2,750 < 3,800 < 4,950**\n\n::: {#fig-price layout-ncol=3}\n\n\n::: {.cell}\n\n```{.r .cell-code}\none_price_g \n```\n\n::: {.cell-output-display}\n![](pricing_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntwo_price_g\n```\n\n::: {.cell-output-display}\n![](pricing_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n\nfive_price_g \n```\n\n::: {.cell-output-display}\n![](pricing_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n서로 다른 3가지 가격정책 비교\n:::\n\n\n\n",
    "supporting": [
      "pricing_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}